### ISSUE TITLE
The build failed because a task wrote output to stderr.

### ISSUE THREAD

**Issue by Ofer-Gal** [Tanddant/TeamsGuestUserOverview#1]
While running:
`gulp build --ship && gulp bundle --ship && gulp package-solution --ship` to package the solution, I got 
"The build failed because a task wrote output to stderr." error.

I know there is a work around but I ended up changing lots of lint rules from 1 to 0.
Only these remain
 Warning - lint - src/webparts/guestUserOverview/components/GuestUserPanel/GuestUserPanel.tsx(60,154): error react/no-unescaped-entities: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.
Warning - lint - src/webparts/guestUserOverview/components/GuestUserPanel/GuestUserPanel.tsx(61,159): error react/no-unescaped-entities: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.
Warning - lint - src/webparts/guestUserOverview/components/GuestUserPanel/GuestUserPanel.tsx(62,123): error react/no-unescaped-entities: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.
Warning - lint - src/webparts/guestUserOverview/components/GuestUserPanel/UserInformation/DeleteUser.tsx(39,49): error react/no-unescaped-entities: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.

So I had to fix the source. for these only. 
fixing == to be === changed the logic and it failed on start. 

Other wise works nice Thank you.

**Comment by Tanddant** [comment]
I just did some testing:

- Cloned repo to a new location (so no uncommited changes would affect it
- Made sure I was running `node v16.20.0`
- Ran  `npm i`
- Ran `gulp serve`, and verified everything ran
- Ran `gulp build --ship && gulp bundle --ship && gulp package-solution --ship`
- Got the same issue as you

How every my normal deployment "command" is slightly different, I run 

`gulp clean`
`gulp bundle --ship`
`gulp package-solution --ship`

(this is package away in an internal company library, but I tested with out)

This results in the sppkg file being generated in the .\sharepoint\solution folder.

As you've noticed there's a bunch of linting warnings, but those shouldn't prevent it from building.

Let me know if you can get it to work, otherwise feel free to shoot me a DM over on [X}(https://x.com/tanddant) and I'll be happy to provide a pre-built .sppkg file 😊

**Comment by Ofer-Gal** [comment]
It was easier to fix the .eslintrc.js file to disregard most warning and fix the other ones. 
Thank you
My admins love your application.
